import type { MockCompany, OptionContract } from '@/types'

export const MOCK_COMPANIES: MockCompany[] = [
  {
    ticker: 'AAPL',
    company_name: 'Apple Inc.',
    industry: 'Technology',
    market_cap_rank: '1st',
    cash_flow: 'Strong',
    earnings_trend: 'Growing',
    debt_to_equity: 'Moderate',
    current_price: 213.5,
    ema_200_week: 198.2,
    description:
      'Apple designs, manufactures, and markets consumer electronics, software, and services. iPhone remains the dominant revenue driver, supplemented by growing Services segment.',
  },
  {
    ticker: 'MSFT',
    company_name: 'Microsoft Corporation',
    industry: 'Technology',
    market_cap_rank: '1st',
    cash_flow: 'Strong',
    earnings_trend: 'Growing',
    debt_to_equity: 'Low',
    current_price: 415.2,
    ema_200_week: 389.8,
    description:
      'Microsoft delivers cloud computing (Azure), enterprise software (Office 365), and gaming (Xbox). Azure growth continues to accelerate, driven by AI integration.',
  },
  {
    ticker: 'NVDA',
    company_name: 'NVIDIA Corporation',
    industry: 'Semiconductors',
    market_cap_rank: '1st',
    cash_flow: 'Strong',
    earnings_trend: 'Growing',
    debt_to_equity: 'Low',
    current_price: 118.4,
    ema_200_week: 108.6,
    description:
      'NVIDIA dominates the AI accelerator market with its H100/H200 GPUs. Data center revenue has surpassed gaming, and demand from hyperscalers remains insatiable.',
  },
  {
    ticker: 'JPM',
    company_name: 'JPMorgan Chase & Co.',
    industry: 'Financial',
    market_cap_rank: '1st',
    cash_flow: 'Strong',
    earnings_trend: 'Growing',
    debt_to_equity: 'Moderate',
    current_price: 222.8,
    ema_200_week: 208.4,
    description:
      'JPMorgan is the largest U.S. bank by assets, with strong investment banking, consumer banking, and asset management franchises. Benefiting from higher-for-longer rate environment.',
  },
  {
    ticker: 'UNH',
    company_name: 'UnitedHealth Group Inc.',
    industry: 'Healthcare',
    market_cap_rank: '1st',
    cash_flow: 'Strong',
    earnings_trend: 'Growing',
    debt_to_equity: 'Low',
    current_price: 524.6,
    ema_200_week: 489.2,
    description:
      'UnitedHealth is the largest U.S. health insurer, operating through UnitedHealthcare and Optum. Strong cash generation and consistent earnings growth make it a healthcare bellwether.',
  },
  {
    ticker: 'HD',
    company_name: 'The Home Depot Inc.',
    industry: 'Consumer Products',
    market_cap_rank: '1st',
    cash_flow: 'Strong',
    earnings_trend: 'Stable',
    debt_to_equity: 'High',
    current_price: 362.4,
    ema_200_week: 341.8,
    description:
      'Home Depot is the world\'s largest home improvement retailer. Pro customer segment drives disproportionate revenue. Housing turnover slowdown is a near-term headwind.',
  },
  {
    ticker: 'AMZN',
    company_name: 'Amazon.com Inc.',
    industry: 'Technology',
    market_cap_rank: '2nd',
    cash_flow: 'Strong',
    earnings_trend: 'Growing',
    debt_to_equity: 'Moderate',
    current_price: 198.6,
    ema_200_week: 183.4,
    description:
      'Amazon operates e-commerce, cloud (AWS), advertising, and logistics businesses. AWS remains the profit engine while advertising is an emerging high-margin segment.',
  },
]

// Canonical mock option contracts — mirrors what's seeded in DB
// These are used when Supabase is not yet configured
export const MOCK_OPTION_CONTRACTS: Record<string, OptionContract[]> = {
  AAPL: [
    {
      id: 'mock-aapl-1',
      ticker: 'AAPL',
      option_type: 'CALL',
      expiration_date: '2027-01-15',
      strike_price: 200,
      current_premium: 18.5,
      all_time_high_premium: 32.0,
      depreciation_pct: 42.19,
      implied_volatility: 0.285,
      delta: 0.52,
      theta: -0.045,
      volume: 1250,
      open_interest: 8500,
      is_mock: true,
    },
    {
      id: 'mock-aapl-2',
      ticker: 'AAPL',
      option_type: 'CALL',
      expiration_date: '2027-06-18',
      strike_price: 210,
      current_premium: 15.2,
      all_time_high_premium: 26.0,
      depreciation_pct: 41.54,
      implied_volatility: 0.292,
      delta: 0.48,
      theta: -0.038,
      volume: 890,
      open_interest: 5200,
      is_mock: true,
    },
    {
      id: 'mock-aapl-3',
      ticker: 'AAPL',
      option_type: 'CALL',
      expiration_date: '2027-01-15',
      strike_price: 220,
      current_premium: 12.4,
      all_time_high_premium: 21.5,
      depreciation_pct: 42.33,
      implied_volatility: 0.301,
      delta: 0.42,
      theta: -0.032,
      volume: 650,
      open_interest: 4100,
      is_mock: true,
    },
  ],
  MSFT: [
    {
      id: 'mock-msft-1',
      ticker: 'MSFT',
      option_type: 'CALL',
      expiration_date: '2027-01-15',
      strike_price: 420,
      current_premium: 45.2,
      all_time_high_premium: 78.0,
      depreciation_pct: 42.05,
      implied_volatility: 0.265,
      delta: 0.54,
      theta: -0.062,
      volume: 980,
      open_interest: 6200,
      is_mock: true,
    },
    {
      id: 'mock-msft-2',
      ticker: 'MSFT',
      option_type: 'CALL',
      expiration_date: '2027-06-18',
      strike_price: 440,
      current_premium: 38.5,
      all_time_high_premium: 65.0,
      depreciation_pct: 40.77,
      implied_volatility: 0.272,
      delta: 0.49,
      theta: -0.054,
      volume: 720,
      open_interest: 4800,
      is_mock: true,
    },
    {
      id: 'mock-msft-3',
      ticker: 'MSFT',
      option_type: 'CALL',
      expiration_date: '2027-01-15',
      strike_price: 460,
      current_premium: 31.8,
      all_time_high_premium: 55.0,
      depreciation_pct: 42.18,
      implied_volatility: 0.28,
      delta: 0.44,
      theta: -0.046,
      volume: 520,
      open_interest: 3600,
      is_mock: true,
    },
  ],
  NVDA: [
    {
      id: 'mock-nvda-1',
      ticker: 'NVDA',
      option_type: 'CALL',
      expiration_date: '2027-01-15',
      strike_price: 120,
      current_premium: 28.4,
      all_time_high_premium: 48.5,
      depreciation_pct: 41.44,
      implied_volatility: 0.425,
      delta: 0.56,
      theta: -0.082,
      volume: 2150,
      open_interest: 12500,
      is_mock: true,
    },
    {
      id: 'mock-nvda-2',
      ticker: 'NVDA',
      option_type: 'CALL',
      expiration_date: '2027-06-18',
      strike_price: 130,
      current_premium: 23.6,
      all_time_high_premium: 40.5,
      depreciation_pct: 41.73,
      implied_volatility: 0.438,
      delta: 0.51,
      theta: -0.074,
      volume: 1680,
      open_interest: 9800,
      is_mock: true,
    },
    {
      id: 'mock-nvda-3',
      ticker: 'NVDA',
      option_type: 'CALL',
      expiration_date: '2027-01-15',
      strike_price: 140,
      current_premium: 19.2,
      all_time_high_premium: 33.0,
      depreciation_pct: 41.82,
      implied_volatility: 0.452,
      delta: 0.46,
      theta: -0.065,
      volume: 1250,
      open_interest: 7200,
      is_mock: true,
    },
  ],
  JPM: [
    {
      id: 'mock-jpm-1',
      ticker: 'JPM',
      option_type: 'CALL',
      expiration_date: '2027-01-15',
      strike_price: 230,
      current_premium: 22.8,
      all_time_high_premium: 39.0,
      depreciation_pct: 41.54,
      implied_volatility: 0.242,
      delta: 0.53,
      theta: -0.038,
      volume: 780,
      open_interest: 5200,
      is_mock: true,
    },
    {
      id: 'mock-jpm-2',
      ticker: 'JPM',
      option_type: 'CALL',
      expiration_date: '2027-06-18',
      strike_price: 240,
      current_premium: 18.9,
      all_time_high_premium: 32.5,
      depreciation_pct: 41.85,
      implied_volatility: 0.251,
      delta: 0.485,
      theta: -0.033,
      volume: 580,
      open_interest: 3900,
      is_mock: true,
    },
    {
      id: 'mock-jpm-3',
      ticker: 'JPM',
      option_type: 'CALL',
      expiration_date: '2027-01-15',
      strike_price: 250,
      current_premium: 15.2,
      all_time_high_premium: 26.0,
      depreciation_pct: 41.54,
      implied_volatility: 0.26,
      delta: 0.435,
      theta: -0.028,
      volume: 420,
      open_interest: 2800,
      is_mock: true,
    },
  ],
  UNH: [
    {
      id: 'mock-unh-1',
      ticker: 'UNH',
      option_type: 'CALL',
      expiration_date: '2027-01-15',
      strike_price: 550,
      current_premium: 52.4,
      all_time_high_premium: 89.0,
      depreciation_pct: 41.12,
      implied_volatility: 0.218,
      delta: 0.515,
      theta: -0.075,
      volume: 420,
      open_interest: 2800,
      is_mock: true,
    },
    {
      id: 'mock-unh-2',
      ticker: 'UNH',
      option_type: 'CALL',
      expiration_date: '2027-06-18',
      strike_price: 580,
      current_premium: 42.8,
      all_time_high_premium: 74.0,
      depreciation_pct: 42.16,
      implied_volatility: 0.225,
      delta: 0.47,
      theta: -0.065,
      volume: 310,
      open_interest: 2100,
      is_mock: true,
    },
    {
      id: 'mock-unh-3',
      ticker: 'UNH',
      option_type: 'CALL',
      expiration_date: '2027-01-15',
      strike_price: 600,
      current_premium: 34.6,
      all_time_high_premium: 59.5,
      depreciation_pct: 41.85,
      implied_volatility: 0.233,
      delta: 0.42,
      theta: -0.055,
      volume: 240,
      open_interest: 1600,
      is_mock: true,
    },
  ],
  HD: [
    {
      id: 'mock-hd-1',
      ticker: 'HD',
      option_type: 'CALL',
      expiration_date: '2027-01-15',
      strike_price: 360,
      current_premium: 34.2,
      all_time_high_premium: 58.0,
      depreciation_pct: 41.03,
      implied_volatility: 0.232,
      delta: 0.525,
      theta: -0.052,
      volume: 560,
      open_interest: 3800,
      is_mock: true,
    },
    {
      id: 'mock-hd-2',
      ticker: 'HD',
      option_type: 'CALL',
      expiration_date: '2027-06-18',
      strike_price: 380,
      current_premium: 27.8,
      all_time_high_premium: 47.5,
      depreciation_pct: 41.47,
      implied_volatility: 0.24,
      delta: 0.48,
      theta: -0.045,
      volume: 420,
      open_interest: 2900,
      is_mock: true,
    },
    {
      id: 'mock-hd-3',
      ticker: 'HD',
      option_type: 'CALL',
      expiration_date: '2027-01-15',
      strike_price: 400,
      current_premium: 22.4,
      all_time_high_premium: 38.5,
      depreciation_pct: 41.82,
      implied_volatility: 0.248,
      delta: 0.43,
      theta: -0.038,
      volume: 310,
      open_interest: 2100,
      is_mock: true,
    },
  ],
  AMZN: [
    {
      id: 'mock-amzn-1',
      ticker: 'AMZN',
      option_type: 'CALL',
      expiration_date: '2027-01-15',
      strike_price: 200,
      current_premium: 26.8,
      all_time_high_premium: 46.0,
      depreciation_pct: 41.74,
      implied_volatility: 0.315,
      delta: 0.535,
      theta: -0.058,
      volume: 1450,
      open_interest: 9200,
      is_mock: true,
    },
    {
      id: 'mock-amzn-2',
      ticker: 'AMZN',
      option_type: 'CALL',
      expiration_date: '2027-06-18',
      strike_price: 215,
      current_premium: 21.6,
      all_time_high_premium: 37.0,
      depreciation_pct: 41.62,
      implied_volatility: 0.324,
      delta: 0.49,
      theta: -0.051,
      volume: 1080,
      open_interest: 7100,
      is_mock: true,
    },
    {
      id: 'mock-amzn-3',
      ticker: 'AMZN',
      option_type: 'CALL',
      expiration_date: '2027-01-15',
      strike_price: 230,
      current_premium: 17.2,
      all_time_high_premium: 29.5,
      depreciation_pct: 41.69,
      implied_volatility: 0.335,
      delta: 0.44,
      theta: -0.044,
      volume: 780,
      open_interest: 5200,
      is_mock: true,
    },
  ],
}

// Weekly opportunity highlights — high-score companies for dashboard
export const WEEKLY_OPPORTUNITIES = [
  {
    ticker: 'MSFT',
    company_name: 'Microsoft Corporation',
    industry: 'Technology',
    score: 94,
    tagline: 'Azure AI tailwinds with pristine balance sheet trading near 200-week EMA.',
  },
  {
    ticker: 'NVDA',
    company_name: 'NVIDIA Corporation',
    industry: 'Semiconductors',
    score: 92,
    tagline: 'AI infrastructure demand remains insatiable; stock consolidating near key support.',
  },
  {
    ticker: 'JPM',
    company_name: 'JPMorgan Chase',
    industry: 'Financial',
    score: 88,
    tagline: 'Best-in-class bank with strong earnings and favorable rate environment.',
  },
]
